apiVersion: v1
kind: Namespace
metadata:
  name: pro
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.global.argocd.controller }}
{{- end }}  