kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Values.argocd.group }}-1
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ $.Values.argocd.group }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin