# Default values for gitops setup

global:
  render: true
  argocd:
    enabled: true
    controller: openshift-operators
  operators: 
    enabled: true
  rbac: 
    enabled: true 
  namespace: openshift-operators
  domain: sandbox549
  sno:
    1:
      token: ''
    2:
      token: ''
    3: 
      token: ''