{{- range $key, $val := $.Values.clusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}-oauth
  namespace: {{ $val.applicationNamespace }}
spec:
  destination:
    server: {{ $val.destination }}
    namespace: ''
  project: {{ $val.project }}
  source:
    helm:
      valueFiles:
        - values-oauth.yaml
    path: {{ $val.code.path }}
    repoURL: {{ $val.code.repo }}
    targetRevision: {{ $val.code.target }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}      