kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials # To be defined parameters
  namespace: openshift-operators # argocd namespace
type: Opaque
stringData:
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_ROLE: "argocd"
  AVP_TYPE: "vault"
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"