kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-repo-server
  namespace: openshift-operators
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - 'secrets'