# PENDING

apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin # To be defined parameters
  namespace: openshift-operators
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      init:
       command:
          - bash
          - "-c"
          - |
            echo "helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f $ARGOCD_ENV_HELM_FILES . --include-crds --debug"
            helm dependency build
      generate:
        command:
          - bash
          - "-c"
          - |
             helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f values.yaml . | argocd-vault-plugin generate -s openshift-operators:argocd-vault-plugin-credentials -
            
      lockRepo: false
